# Generated by Django 4.2.7 on 2023-11-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='nome_do_contato_de_emergenica',
            new_name='nome_do_contato_de_emergencia',
        ),
    ]
