# Generated by Django 4.2.7 on 2023-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_especies_genero_porte_raca_alter_animais_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='nome_cientifico',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
