# Generated by Django 4.2.7 on 2023-11-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_especies_nome_cientifico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animais',
            options={'ordering': ['nome'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Registro de animais'},
        ),
        migrations.AlterModelOptions(
            name='especies',
            options={'ordering': ['especie'], 'verbose_name': 'Espécie'},
        ),
        migrations.RemoveField(
            model_name='animais',
            name='origem',
        ),
        migrations.AddField(
            model_name='animais',
            name='comportamento',
            field=models.CharField(default='Comportamento padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='animais',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_URL'),
        ),
        migrations.AddField(
            model_name='raca',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='animais.especies'),
        ),
    ]
