# Generated by Django 4.2.7 on 2023-11-22 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereço_residencial', models.CharField(max_length=255)),
                ('endereço_email', models.EmailField(max_length=254)),
                ('numero_de_telefone', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_de_residencia', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa')], default='Casa', max_length=12)),
                ('tipo_de_propriedade', models.CharField(choices=[('Própria', 'Própria'), ('Alugada', 'Alugada')], default='Própria', max_length=8)),
                ('permissao_para_animais_no_local', models.BooleanField(default=False)),
                ('motivacao_para_adotar', models.TextField()),
                ('o_que_espera_da_adocao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceita', 'Aceita'), ('Recusada', 'Recusada')], default='Pendente', max_length=20)),
            ],
        ),
    ]
