# Generated by Django 4.2.7 on 2023-11-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_solicitacaoadocao_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoadocao',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Formulário de adoção', 'verbose_name_plural': 'Formulários de adoção'},
        ),
    ]
