# Generated by Django 4.2.7 on 2023-11-24 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0010_alter_raca_especie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_solicitacaoadocao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoadocao',
            name='animal_a_adotar',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='animais.animais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaoadocao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
